# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f166862c9e05fc10343f6829aa7ec66828598784a9f4dcef242bed4574fb55057f4a0b97ca0e1f3c7190834d32926ca0dae8f73e0e5487158ccdf7644337bdb

test:
  secret_key_base: 4e056c899d30409472aa5bb2504ae15722c0337272d91c3181b2c65f6d1bc3100d75fa10f1634f37a0a7db68ef1add6304e79da8e62ab05f74ebc23d7bbf7982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
